import SEOHead from '@/components/SEOHead';

const Section = ({ title, children }) => (
  <section className="space-y-3">
    <h2 className="text-xl font-bold text-[#1a1a1a]">{title}</h2>
    <div className="space-y-3 text-[#5f5a54] leading-7">{children}</div>
  </section>
);

export default function PrivacyPolicy() {
  return (
    <main className="bg-[#f8f5ef] py-16 md:py-24">
      <SEOHead
        title="Privacy Policy | Outright Landscape"
        description="Learn how Outright Landscape handles information submitted through its website and uses website analytics."
        canonicalUrl="https://outrightlandscape.com/privacy-policy"
      />
      <article className="mx-auto max-w-3xl px-5 sm:px-8">
        <header className="mb-12 border-b border-[#ddd5c8] pb-8">
          <p className="mb-3 text-xs font-bold uppercase tracking-[0.2em] text-[#c45d2c]">Outright Landscape</p>
          <h1 className="text-4xl font-bold tracking-tight text-[#1a1a1a] md:text-5xl">Privacy Policy</h1>
          <p className="mt-4 text-sm text-[#777068]">Effective August 1, 2026</p>
        </header>

        <div className="space-y-10">
          <Section title="Information we collect">
            <p>
              When you request an estimate or book an appointment, we may collect your name, phone number,
              email address, city, project details, requested service, and preferred appointment date and time.
            </p>
            <p>
              Our website also records basic visit and interaction data, such as pages viewed and clicks on
              contact buttons, through Google advertising and analytics technology and our website platform.
              Those services may use cookies or similar browser technologies.
            </p>
          </Section>

          <Section title="How we use information">
            <p>
              We use submitted information to respond to inquiries, prepare estimates, schedule and confirm
              appointments, provide requested services, and maintain business records. Website interaction data
              helps us understand site performance and measure inquiries generated by our advertising.
            </p>
          </Section>

          <Section title="Service providers">
            <p>
              Information may be processed by providers that support this website, its database, email delivery,
              appointment handling, and analytics. Those providers process information to perform services for us
              under their own applicable terms and privacy practices.
            </p>
          </Section>

          <Section title="Your choices">
            <p>
              You can limit cookies through your browser settings. Blocking cookies may affect some site features.
              You may also contact us to ask about, correct, or request deletion of personal information you
              submitted through this website, subject to records we need to retain for legitimate business or legal reasons.
            </p>
          </Section>

          <Section title="Data security and retention">
            <p>
              We use reasonable measures intended to protect information, but no internet transmission or storage
              system is guaranteed to be completely secure. We retain information only as long as reasonably needed
              for the purposes described above and applicable business or legal requirements.
            </p>
          </Section>

          <Section title="Updates and contact">
            <p>
              We may update this policy as our website or practices change. The effective date above identifies the
              current version. For privacy questions or requests, call Outright Landscape at{' '}
              <a className="font-semibold text-[#2d5a27] underline underline-offset-4" href="tel:626-343-6028">
                (626) 343-6028
              </a>.
            </p>
          </Section>
        </div>
      </article>
    </main>
  );
}
